/**
 * Apple signed-payload verification.
 *
 * Run against a REAL ECDSA P-256 certificate chain generated by
 * backend/scripts/make-apple-test-fixtures.mjs. The fixtures are not Apple's
 * certificates — they are a stand-in with the same shape — but every signature
 * here is genuine, so the verifier is exercised rather than mocked.
 *
 * The test that matters is `rogue chain is rejected`: a completely independent,
 * internally consistent chain. Every check except the root pin passes for it.
 * If that test goes green while the pin is broken, this whole module is theatre.
 */

import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import {
  JwsError,
  decodeUnverified,
  verifyAppleSignedPayload,
  verifyTransaction,
  type AppleNotificationPayload,
  type AppleTransactionPayload,
} from '../shared/apple/jws.ts';
import {
  CertificateError,
  parseCertificateBase64,
  verifyCertificateChain,
} from '../shared/apple/x509.ts';
import {
  DerError,
  TAG,
  base64ToBytes,
  bytesEqual,
  derEcdsaToRaw,
  expect as expectDer,
  readNode,
  readTime,
} from '../shared/apple/der.ts';

const here = dirname(fileURLToPath(import.meta.url));
const fixtures = JSON.parse(
  readFileSync(join(here, '../shared/fixtures/apple-chain.json'), 'utf8'),
) as {
  validAt: string;
  trustedRootDer: string;
  rogueRootDer: string;
  chain: { leafDer: string; intermediateDer: string; rootDer: string };
  tokens: Record<string, string>;
  payloads: Record<string, Record<string, unknown>>;
};

const trustedRoot = base64ToBytes(fixtures.trustedRootDer);
const rogueRoot = base64ToBytes(fixtures.rogueRootDer);
const now = new Date(fixtures.validAt);

const BUNDLE_ID = 'com.yourcompany.before';

function chain() {
  return [
    parseCertificateBase64(fixtures.chain.leafDer),
    parseCertificateBase64(fixtures.chain.intermediateDer),
    parseCertificateBase64(fixtures.chain.rootDer),
  ];
}

// ---------------------------------------------------------------------------
// DER primitives
// ---------------------------------------------------------------------------

test('DER reader handles short and long form lengths', () => {
  // SEQUENCE, 1 byte of content.
  const short = new Uint8Array([0x30, 0x01, 0x00]);
  const shortNode = readNode(short, 0);
  assert.equal(shortNode.tag, TAG.SEQUENCE);
  assert.equal(shortNode.contentEnd - shortNode.contentStart, 1);

  // SEQUENCE, 0x81 0x80 => 128 bytes of content.
  const long = new Uint8Array(3 + 128);
  long[0] = 0x30;
  long[1] = 0x81;
  long[2] = 0x80;
  const longNode = readNode(long, 0);
  assert.equal(longNode.contentEnd - longNode.contentStart, 128);
});

test('DER reader rejects indefinite length, which is BER not DER', () => {
  assert.throws(() => readNode(new Uint8Array([0x30, 0x80, 0x00, 0x00]), 0), DerError);
});

test('DER reader rejects content that runs past the buffer', () => {
  assert.throws(() => readNode(new Uint8Array([0x30, 0x10, 0x00]), 0), DerError);
});

test('expect() reports the tag it wanted', () => {
  assert.throws(
    () => expectDer(new Uint8Array([0x02, 0x01, 0x05]), 0, TAG.SEQUENCE, 'Certificate'),
    /expected Certificate/,
  );
});

test('UTCTime and GeneralizedTime both parse, with the RFC 5280 century rule', () => {
  const utc = new Uint8Array([TAG.UTC_TIME, 13, ...new TextEncoder().encode('260924103000Z')]);
  assert.equal(readTime(utc, readNode(utc, 0)).toISOString(), '2026-09-24T10:30:00.000Z');

  // 50..99 means 19xx.
  const legacy = new Uint8Array([TAG.UTC_TIME, 13, ...new TextEncoder().encode('960924103000Z')]);
  assert.equal(readTime(legacy, readNode(legacy, 0)).toISOString(), '1996-09-24T10:30:00.000Z');

  const generalized = new Uint8Array([
    TAG.GENERALIZED_TIME, 15, ...new TextEncoder().encode('20510924103000Z'),
  ]);
  assert.equal(readTime(generalized, readNode(generalized, 0)).toISOString(), '2051-09-24T10:30:00.000Z');
});

test('DER ECDSA signatures convert to the raw form WebCrypto wants', () => {
  // SEQUENCE { INTEGER 0x00FF.., INTEGER 0x01 } — the leading 0x00 is DER's
  // sign byte and must be dropped; the short component must be left-padded.
  const der = new Uint8Array([
    0x30, 0x08,
    0x02, 0x03, 0x00, 0xff, 0xee,
    0x02, 0x01, 0x01,
  ]);
  const raw = derEcdsaToRaw(der, 32);

  assert.equal(raw.length, 64);
  assert.deepEqual([...raw.subarray(30, 32)], [0xff, 0xee], 'r right-aligned, sign byte dropped');
  assert.equal(raw[63], 0x01, 's right-aligned');
  assert.equal(raw[32], 0x00, 's zero-padded on the left');
});

// ---------------------------------------------------------------------------
// Certificate parsing
// ---------------------------------------------------------------------------

test('a real certificate parses into the fields the verifier needs', () => {
  const leaf = parseCertificateBase64(fixtures.chain.leafDer);

  assert.equal(leaf.signatureAlgorithm, '1.2.840.10045.4.3.2', 'ecdsa-with-SHA256');
  assert.equal(leaf.publicKeyAlgorithm, '1.2.840.10045.2.1', 'id-ecPublicKey');
  assert.equal(leaf.publicKeyCurve, '1.2.840.10045.3.1.7', 'prime256v1');
  assert.ok(leaf.tbs.length > 100);
  assert.ok(leaf.spki.length > 50);
  assert.ok(leaf.notBefore < leaf.notAfter);
});

test('the chain links up: each issuer matches the parent subject', () => {
  const [leaf, intermediate, root] = chain();
  assert.ok(bytesEqual(leaf.issuerDer, intermediate.subjectDer));
  assert.ok(bytesEqual(intermediate.issuerDer, root.subjectDer));
  assert.ok(bytesEqual(root.issuerDer, root.subjectDer), 'root is self-signed');
});

test('garbage is rejected as a certificate', () => {
  assert.throws(() => parseCertificateBase64('AAAA'), CertificateError);
});

// ---------------------------------------------------------------------------
// Chain verification
// ---------------------------------------------------------------------------

test('a valid chain verifies and yields the leaf key', async () => {
  const key = await verifyCertificateChain(chain(), { rootCertificate: trustedRoot, now });
  assert.equal(key.type, 'public');
  assert.equal(key.algorithm.name, 'ECDSA');
});

test('THE PIN: an independent, internally valid chain is rejected', async () => {
  // This chain is real and self-consistent. Only the root differs.
  await assert.rejects(
    () => verifyAppleSignedPayload(fixtures.tokens.rogueChain, { rootCertificate: trustedRoot, now }),
    (error: unknown) => error instanceof JwsError && /pinned Apple root/.test(error.message),
  );
});

test('the rogue chain verifies against its OWN root, proving it is well-formed', async () => {
  // Without this, the previous test could be passing because the rogue chain is
  // simply broken, which would prove nothing about the pin.
  const payload = await verifyAppleSignedPayload<AppleTransactionPayload>(
    fixtures.tokens.rogueChain,
    { rootCertificate: rogueRoot, now },
  );
  assert.equal(payload.originalTransactionId, '2000000400000001');
});

test('a chain outside its validity window is rejected', async () => {
  const future = new Date(now.getTime() + 40 * 365 * 86_400_000);
  await assert.rejects(
    () => verifyCertificateChain(chain(), { rootCertificate: trustedRoot, now: future }),
    (error: unknown) => error instanceof CertificateError && /expired/.test(error.message),
  );

  const past = new Date(now.getTime() - 40 * 365 * 86_400_000);
  await assert.rejects(
    () => verifyCertificateChain(chain(), { rootCertificate: trustedRoot, now: past }),
    (error: unknown) => error instanceof CertificateError && /not valid until/.test(error.message),
  );
});

test('a chain with the middle certificate removed is rejected', async () => {
  const [leaf, , root] = chain();
  await assert.rejects(
    () => verifyCertificateChain([leaf, root], { rootCertificate: trustedRoot, now }),
    (error: unknown) => error instanceof CertificateError && /was not issued by/.test(error.message),
  );
});

test('a single self-signed certificate is not a chain', async () => {
  const [leaf] = chain();
  await assert.rejects(
    () => verifyCertificateChain([leaf], { rootCertificate: trustedRoot, now }),
    CertificateError,
  );
});

// ---------------------------------------------------------------------------
// JWS verification
// ---------------------------------------------------------------------------

test('a genuine signed transaction verifies', async () => {
  const payload = await verifyAppleSignedPayload<AppleTransactionPayload>(
    fixtures.tokens.transaction,
    { rootCertificate: trustedRoot, now },
  );

  assert.equal(payload.transactionId, '2000000500000001');
  assert.equal(payload.originalTransactionId, '2000000400000001');
  assert.equal(payload.productId, 'before.plus.yearly');
  assert.equal(payload.bundleId, BUNDLE_ID);
});

test('a tampered signature is rejected', async () => {
  await assert.rejects(
    () => verifyAppleSignedPayload(fixtures.tokens.corruptSignature, { rootCertificate: trustedRoot, now }),
    (error: unknown) => error instanceof JwsError && /does not verify/.test(error.message),
  );
});

test('a tampered PAYLOAD is rejected even though the chain is genuine', async () => {
  const [header, payload, signature] = fixtures.tokens.transaction.split('.');
  const forged = JSON.parse(Buffer.from(payload, 'base64url').toString());
  forged.expiresDate = 99_999_999_999_999; // a free century of Plus
  const forgedSegment = Buffer.from(JSON.stringify(forged)).toString('base64url');

  await assert.rejects(
    () =>
      verifyAppleSignedPayload(`${header}.${forgedSegment}.${signature}`, {
        rootCertificate: trustedRoot,
        now,
      }),
    (error: unknown) => error instanceof JwsError && /does not verify/.test(error.message),
  );
});

test('an algorithm other than ES256 is refused', async () => {
  // "alg": "HS256" with an x5c chain is the classic algorithm-confusion attack.
  await assert.rejects(
    () => verifyAppleSignedPayload(fixtures.tokens.wrongAlgorithm, { rootCertificate: trustedRoot, now }),
    (error: unknown) => error instanceof JwsError && /unsupported JWS algorithm/.test(error.message),
  );
});

test('a JWS with no certificate chain is refused', async () => {
  const header = Buffer.from(JSON.stringify({ alg: 'ES256' })).toString('base64url');
  const payload = Buffer.from(JSON.stringify({ a: 1 })).toString('base64url');
  await assert.rejects(
    () => verifyAppleSignedPayload(`${header}.${payload}.AAAA`, { rootCertificate: trustedRoot, now }),
    (error: unknown) => error instanceof JwsError && /no certificate chain/.test(error.message),
  );
});

test('malformed tokens are refused rather than crashing', async () => {
  for (const token of ['', 'not.a.jws', 'a.b', 'a.b.c.d', '..']) {
    await assert.rejects(
      () => verifyAppleSignedPayload(token, { rootCertificate: trustedRoot, now }),
      JwsError,
      `should have refused "${token}"`,
    );
  }
});

// ---------------------------------------------------------------------------
// Transaction-level checks
// ---------------------------------------------------------------------------

test('a transaction for another app is refused', async () => {
  // A validly-signed transaction from any other App Store app would otherwise
  // verify here and could be replayed to grant Plus.
  await assert.rejects(
    () =>
      verifyTransaction(fixtures.tokens.foreignBundleTransaction, {
        rootCertificate: trustedRoot,
        now,
        expectedBundleId: BUNDLE_ID,
        allowSandbox: true,
      }),
    (error: unknown) => error instanceof JwsError && /com\.someoneelse\.app/.test(error.message),
  );
});

test('a sandbox transaction is refused when sandbox is not allowed', async () => {
  await assert.rejects(
    () =>
      verifyTransaction(fixtures.tokens.sandboxTransaction, {
        rootCertificate: trustedRoot,
        now,
        expectedBundleId: BUNDLE_ID,
        allowSandbox: false,
      }),
    (error: unknown) => error instanceof JwsError && /sandbox/.test(error.message),
  );
});

test('a sandbox transaction is accepted when sandbox is allowed', async () => {
  const result = await verifyTransaction(fixtures.tokens.sandboxTransaction, {
    rootCertificate: trustedRoot,
    now,
    expectedBundleId: BUNDLE_ID,
    allowSandbox: true,
  });
  assert.equal(result.environment, 'sandbox');
});

test('a production transaction reports the production environment', async () => {
  const result = await verifyTransaction(fixtures.tokens.transaction, {
    rootCertificate: trustedRoot,
    now,
    expectedBundleId: BUNDLE_ID,
    allowSandbox: false,
  });
  assert.equal(result.environment, 'production');
  assert.equal(result.transaction.appAccountToken, '2b0b8c5e-9b8a-4c6f-9d1e-7a3f5c2d1e4b');
});

// ---------------------------------------------------------------------------
// Notifications
// ---------------------------------------------------------------------------

test('a notification verifies and its nested transaction verifies separately', async () => {
  const notification = await verifyAppleSignedPayload<AppleNotificationPayload>(
    fixtures.tokens.notification,
    { rootCertificate: trustedRoot, now },
  );

  assert.equal(notification.notificationType, 'DID_RENEW');
  assert.ok(notification.data?.signedTransactionInfo);

  // The nested transaction is its own JWS and gets its own verification. It is
  // not trusted just because the envelope was signed.
  const inner = await verifyTransaction(notification.data.signedTransactionInfo, {
    rootCertificate: trustedRoot,
    now,
    expectedBundleId: BUNDLE_ID,
    allowSandbox: true,
  });
  assert.equal(inner.transaction.productId, 'before.plus.yearly');
});

test('decodeUnverified reads a payload without checking anything', () => {
  // It exists for routing before verification. The name is the warning.
  const payload = decodeUnverified<AppleTransactionPayload>(fixtures.tokens.rogueChain);
  assert.equal(payload.originalTransactionId, '2000000400000001');
});
